--[[
Illarion Server

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>. 
]]
-- INSERT INTO "quests" ("qst_id", "qst_script") VALUES (181, 'quest.bula_glasha_181_galmair');

require("base.common")
module("quest.bula_glasha_181_galmair", package.seeall)

GERMAN = Player.german
ENGLISH = Player.english

-- Insert the quest title here, in both languages
Title = {}
Title[GERMAN] = "Spitzel Informant"
Title[ENGLISH] = "Spy Informant"

-- Insert an extensive description of each status here, in both languages
-- Make sure that the player knows exactly where to go and what to do
Description = {}
Description[GERMAN] = {}
Description[ENGLISH] = {}

Description[GERMAN][1] = "Informationsbedarf für die Don gesammelt. Scout für den Bereich Informations-und töten vier Wespen, euer Lohn ist einem Silberstück."
Description[GERMAN][2] = "."
Description[GERMAN][3] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von einem Silberstück an denjenigen auszuzahlen, der vier Käfer erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][4] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von einem Silberstück an denjenigen auszuzahlen, der vier Käfer erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][5] = "Kehre zu Bula Glasha zurück, um deine Belohnung zu erhalten."
Description[GERMAN][6] = "Die Gegend um Galmair geworden zunehmenden gewalttätigen und das ist der Don-Gewinne zu behindern. Scout für den Bereich Informations-und töten acht Wespen, euer Lohn ist zwei Silberstücke."
Description[GERMAN][7] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][8] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][9] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][10] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][11] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][12] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][13] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][14] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][15] = "Intelligence-Berichte sind für die Sicherheit der Galmair nötig. Scout für den Bereich Informations-und töten zwölf Wespen, euer Lohn ist drei Silbermünzen."
Description[GERMAN][16] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][17] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][18] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][19] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][20] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][21] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][22] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][23] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][24] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][25] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][26] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][27] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][28] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][29] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][30] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][31] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][32] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][33] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][34] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][35] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][36] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][37] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][38] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][39] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][40] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][41] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][42] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][43] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][44] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][45] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][46] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][47] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][48] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][49] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][50] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][51] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][52] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][53] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][54] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][55] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][56] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][57] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][58] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][59] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][60] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][61] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][62] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][63] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][64] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][65] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][66] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][67] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][68] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][69] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][70] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][71] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][72] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][73] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][74] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][75] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][76] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][77] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][78] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][79] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][80] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][81] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][82] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][83] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][84] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][85] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][86] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][87] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][88] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][89] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][90] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][91] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][92] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][93] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][94] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][95] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][96] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][97] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][98] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][99] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][100] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][101] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][102] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][103] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][104] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][105] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][106] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][107] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][108] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][109] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][110] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][111] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][112] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][113] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][114] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][115] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][116] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][117] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][118] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][119] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][120] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][121] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][122] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][123] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][124] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][125] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][126] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][127] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][128] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][129] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][130] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][131] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][132] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][133] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][134] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][135] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][136] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][137] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][138] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][139] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][140] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][141] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][142] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][143] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][144] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][145] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][146] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][147] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][148] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][149] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][150] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][151] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][152] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][153] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][154] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][155] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][156] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][157] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][158] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][159] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][160] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][161] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][162] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][163] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][164] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][165] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][166] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][167] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][168] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][169] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][170] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][171] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][172] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][173] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][174] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][175] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][176] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][177] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][178] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][179] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][180] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][181] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][182] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][183] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][184] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][185] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][186] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][187] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][188] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][189] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."

Description[ENGLISH][1] = "There is information to be gathered for the Don. Scout the area for information and kill four wasps, your reward is one silver coin."
Description[ENGLISH][2] = "There is information to be gathered for the Don. Scout the area for information and kill four wasps, your reward is one silver coin."
Description[ENGLISH][3] = "There is information to be gathered for the Don. Scout the area for information and kill four wasps, your reward is one silver coin."
Description[ENGLISH][4] = "There is information to be gathered for the Don. Scout the area for information and kill four wasps, your reward is one silver coin."
Description[ENGLISH][5] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][6] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight wasps, your reward is two silver coins."
Description[ENGLISH][7] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight wasps, your reward is two silver coins."
Description[ENGLISH][8] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight wasps, your reward is two silver coins."
Description[ENGLISH][9] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight wasps, your reward is two silver coins."
Description[ENGLISH][10] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight wasps, your reward is two silver coins."
Description[ENGLISH][11] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight wasps, your reward is two silver coins."
Description[ENGLISH][12] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight wasps, your reward is two silver coins."
Description[ENGLISH][13] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight wasps, your reward is two silver coins."
Description[ENGLISH][14] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][15] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][16] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][17] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][18] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][19] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][20] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][21] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][22] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][23] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][24] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][25] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][26] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve wasps, your reward is three silver coins."
Description[ENGLISH][27] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][28] = "There is information to be gathered for the Don. Scout the area for information and kill four slimes your reward is two silver coins."
Description[ENGLISH][29] = "There is information to be gathered for the Don. Scout the area for information and kill four slimes your reward is two silver coins."
Description[ENGLISH][30] = "There is information to be gathered for the Don. Scout the area for information and kill four slimes your reward is two silver coins."
Description[ENGLISH][31] = "There is information to be gathered for the Don. Scout the area for information and kill four slimes your reward is two silver coins."
Description[ENGLISH][32] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][33] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight slimes, your reward is four silver coins."
Description[ENGLISH][34] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight slimes, your reward is four silver coins."
Description[ENGLISH][35] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight slimes, your reward is four silver coins."
Description[ENGLISH][36] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight slimes, your reward is four silver coins."
Description[ENGLISH][37] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight slimes, your reward is four silver coins."
Description[ENGLISH][38] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight slimes, your reward is four silver coins."
Description[ENGLISH][39] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight slimes, your reward is four silver coins."
Description[ENGLISH][40] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight slimes, your reward is four silver coins."
Description[ENGLISH][41] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][42] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][43] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][44] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][45] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][46] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][47] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][48] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][49] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][50] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][51] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][52] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][53] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve slimes, your reward is six silver coins."
Description[ENGLISH][54] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][55] = "There is information to be gathered for the Don. Scout the area for information and kill four dogs your reward is three silver coins."
Description[ENGLISH][56] = "There is information to be gathered for the Don. Scout the area for information and kill four dogs your reward is three silver coins."
Description[ENGLISH][57] = "There is information to be gathered for the Don. Scout the area for information and kill four dogs your reward is three silver coins."
Description[ENGLISH][58] = "There is information to be gathered for the Don. Scout the area for information and kill four dogs your reward is three silver coins."
Description[ENGLISH][59] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][60] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight dogs, your reward is six silver coins."
Description[ENGLISH][61] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight dogs, your reward is six silver coins."
Description[ENGLISH][62] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight dogs, your reward is six silver coins."
Description[ENGLISH][63] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight dogs, your reward is six silver coins."
Description[ENGLISH][64] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight dogs, your reward is six silver coins."
Description[ENGLISH][65] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight dogs, your reward is six silver coins."
Description[ENGLISH][66] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight dogs, your reward is six silver coins."
Description[ENGLISH][67] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight dogs, your reward is six silver coins."
Description[ENGLISH][68] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][69] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][70] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][71] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][72] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][73] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][74] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][75] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][76] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][77] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][78] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][79] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][80] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve dogs, your reward is nine silver coins."
Description[ENGLISH][81] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][82] = "There is information to be gathered for the Don. Scout the area for information and kill four foxes your reward is four silver coins."
Description[ENGLISH][83] = "There is information to be gathered for the Don. Scout the area for information and kill four foxes your reward is four silver coins."
Description[ENGLISH][84] = "There is information to be gathered for the Don. Scout the area for information and kill four foxes your reward is four silver coins."
Description[ENGLISH][85] = "There is information to be gathered for the Don. Scout the area for information and kill four foxes your reward is four silver coins."
Description[ENGLISH][86] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][87] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight foxes, your reward is eight silver coins."
Description[ENGLISH][88] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight foxes, your reward is eight silver coins."
Description[ENGLISH][89] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight foxes, your reward is eight silver coins."
Description[ENGLISH][90] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight foxes, your reward is eight silver coins."
Description[ENGLISH][91] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight foxes, your reward is eight silver coins."
Description[ENGLISH][92] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight foxes, your reward is eight silver coins."
Description[ENGLISH][93] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight foxes, your reward is eight silver coins."
Description[ENGLISH][94] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight foxes, your reward is eight silver coins."
Description[ENGLISH][95] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][96] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][97] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][98] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][99] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][100] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][101] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][102] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][103] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][104] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][105] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][106] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][107] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve foxes, your reward is twelve silver coins."
Description[ENGLISH][108] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][109] = "There is information to be gathered for the Don. Scout the area for information and kill four rats your reward is six silver coins."
Description[ENGLISH][110] = "There is information to be gathered for the Don. Scout the area for information and kill four rats your reward is six silver coins."
Description[ENGLISH][111] = "There is information to be gathered for the Don. Scout the area for information and kill four rats your reward is six silver coins."
Description[ENGLISH][112] = "There is information to be gathered for the Don. Scout the area for information and kill four rats your reward is six silver coins."
Description[ENGLISH][113] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][114] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight rats, your reward is twelve silver coins."
Description[ENGLISH][115] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight rats, your reward is twelve silver coins."
Description[ENGLISH][116] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight rats, your reward is twelve silver coins."
Description[ENGLISH][117] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight rats, your reward is twelve silver coins."
Description[ENGLISH][118] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight rats, your reward is twelve silver coins."
Description[ENGLISH][119] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight rats, your reward is twelve silver coins."
Description[ENGLISH][120] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight rats, your reward is twelve silver coins."
Description[ENGLISH][121] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight rats, your reward is twelve silver coins."
Description[ENGLISH][122] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][123] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][124] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][125] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][126] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][127] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][128] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][129] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][130] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][131] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][132] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][133] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][134] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve rats, your reward is eighteen silver coins."
Description[ENGLISH][135] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][136] = "There is information to be gathered for the Don. Scout the area for information and kill four bear your reward is eight silver coins."
Description[ENGLISH][137] = "There is information to be gathered for the Don. Scout the area for information and kill four bear your reward is eight silver coins."
Description[ENGLISH][138] = "There is information to be gathered for the Don. Scout the area for information and kill four bear your reward is eight silver coins."
Description[ENGLISH][139] = "There is information to be gathered for the Don. Scout the area for information and kill four bear your reward is eight silver coins."
Description[ENGLISH][140] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][141] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight bears, your reward is sixteen silver coins."
Description[ENGLISH][142] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight bears, your reward is sixteen silver coins."
Description[ENGLISH][143] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight bears, your reward is sixteen silver coins."
Description[ENGLISH][144] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight bears, your reward is sixteen silver coins."
Description[ENGLISH][145] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight bears, your reward is sixteen silver coins."
Description[ENGLISH][146] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight bears, your reward is sixteen silver coins."
Description[ENGLISH][147] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight bears, your reward is sixteen silver coins."
Description[ENGLISH][148] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight bears, your reward is sixteen silver coins."
Description[ENGLISH][149] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][150] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][151] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][152] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][153] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][154] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][155] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][156] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][157] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][158] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][159] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][160] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][161] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve bears, your reward is twenty four silver coins."
Description[ENGLISH][162] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][163] = "There is information to be gathered for the Don. Scout the area for information and kill four troll your reward is ten silver coins."
Description[ENGLISH][164] = "There is information to be gathered for the Don. Scout the area for information and kill four troll your reward is ten silver coins."
Description[ENGLISH][165] = "There is information to be gathered for the Don. Scout the area for information and kill four troll your reward is ten silver coins."
Description[ENGLISH][166] = "There is information to be gathered for the Don. Scout the area for information and kill four troll your reward is ten silver coins."
Description[ENGLISH][167] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][168] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight trolls, your reward is twenty silver coins."
Description[ENGLISH][169] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight trolls, your reward is twenty silver coins."
Description[ENGLISH][170] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight trolls, your reward is twenty silver coins."
Description[ENGLISH][171] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight trolls, your reward is twenty silver coins."
Description[ENGLISH][172] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight trolls, your reward is twenty silver coins."
Description[ENGLISH][173] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight trolls, your reward is twenty silver coins."
Description[ENGLISH][174] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight trolls, your reward is twenty silver coins."
Description[ENGLISH][175] = "The area around Galmair has become increasing violent and this is hindering the Don's profits.  Scout the area for information and kill eight trolls, your reward is twenty silver coins."
Description[ENGLISH][176] = "Return to Bula Glasha to claim your reward."
Description[ENGLISH][177] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][178] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][179] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][180] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][181] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][182] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][183] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][184] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][185] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][186] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][187] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][188] = "Intelligence reports are needed for the safety of Galmair.  Scout the area for information and kill twelve trolls, your reward is thirty silver coins."
Description[ENGLISH][189] = "Return to Bula Glasha to claim your reward."


-- Insert the position of the quest start here (probably the position of an NPC or item)
Start = {407, 232, 0}

-- For each status insert a list of positions where the quest will continue, i.e. a new status can be reached there
QuestTarget = {}
QuestTarget[1] = {position(407, 232, 0)} -- Bula
QuestTarget[2] = {position(407, 232, 0)} -- Bula
QuestTarget[3] = {position(407, 232, 0)} -- Bula
QuestTarget[4] = {position(407, 232, 0)} -- Bula
QuestTarget[5] = {position(407, 232, 0)} -- Bula
QuestTarget[6] = {position(407, 232, 0)} -- Bula
QuestTarget[7] = {position(407, 232, 0)} -- Bula
QuestTarget[8] = {position(407, 232, 0)} -- Bula
QuestTarget[9] = {position(407, 232, 0)} -- Bula
QuestTarget[10] = {position(407, 232, 0)} -- Bula
QuestTarget[11] = {position(407, 232, 0)} -- Bula
QuestTarget[12] = {position(407, 232, 0)} -- Bula
QuestTarget[13] = {position(407, 232, 0)} -- Bula
QuestTarget[14] = {position(407, 232, 0)} -- Bula
QuestTarget[15] = {position(407, 232, 0)} -- Bula
QuestTarget[16] = {position(407, 232, 0)} -- Bula
QuestTarget[17] = {position(407, 232, 0)} -- Bula
QuestTarget[18] = {position(407, 232, 0)} -- Bula
QuestTarget[19] = {position(407, 232, 0)} -- Bula
QuestTarget[20] = {position(407, 232, 0)} -- Bula
QuestTarget[21] = {position(407, 232, 0)} -- Bula
QuestTarget[22] = {position(407, 232, 0)} -- Bula
QuestTarget[23] = {position(407, 232, 0)} -- Bula
QuestTarget[24] = {position(407, 232, 0)} -- Bula
QuestTarget[25] = {position(407, 232, 0)} -- Bula
QuestTarget[26] = {position(407, 232, 0)} -- Bula
QuestTarget[27] = {position(407, 232, 0)} -- Bula
QuestTarget[28] = {position(407, 232, 0)} -- Bula
QuestTarget[29] = {position(407, 232, 0)} -- Bula
QuestTarget[30] = {position(407, 232, 0)} -- Bula
QuestTarget[31] = {position(407, 232, 0)} -- Bula
QuestTarget[32] = {position(407, 232, 0)} -- Bula
QuestTarget[33] = {position(407, 232, 0)} -- Bula
QuestTarget[34] = {position(407, 232, 0)} -- Bula
QuestTarget[35] = {position(407, 232, 0)} -- Bula
QuestTarget[36] = {position(407, 232, 0)} -- Bula
QuestTarget[37] = {position(407, 232, 0)} -- Bula
QuestTarget[38] = {position(407, 232, 0)} -- Bula
QuestTarget[39] = {position(407, 232, 0)} -- Bula
QuestTarget[40] = {position(407, 232, 0)} -- Bula
QuestTarget[41] = {position(407, 232, 0)} -- Bula
QuestTarget[42] = {position(407, 232, 0)} -- Bula
QuestTarget[43] = {position(407, 232, 0)} -- Bula
QuestTarget[44] = {position(407, 232, 0)} -- Bula
QuestTarget[45] = {position(407, 232, 0)} -- Bula
QuestTarget[46] = {position(407, 232, 0)} -- Bula
QuestTarget[47] = {position(407, 232, 0)} -- Bula
QuestTarget[48] = {position(407, 232, 0)} -- Bula
QuestTarget[49] = {position(407, 232, 0)} -- Bula
QuestTarget[50] = {position(407, 232, 0)} -- Bula
QuestTarget[51] = {position(407, 232, 0)} -- Bula
QuestTarget[52] = {position(407, 232, 0)} -- Bula
QuestTarget[53] = {position(407, 232, 0)} -- Bula
QuestTarget[54] = {position(407, 232, 0)} -- Bula
QuestTarget[55] = {position(407, 232, 0)} -- Bula
QuestTarget[56] = {position(407, 232, 0)} -- Bula
QuestTarget[57] = {position(407, 232, 0)} -- Bula
QuestTarget[58] = {position(407, 232, 0)} -- Bula
QuestTarget[59] = {position(407, 232, 0)} -- Bula
QuestTarget[60] = {position(407, 232, 0)} -- Bula
QuestTarget[61] = {position(407, 232, 0)} -- Bula
QuestTarget[62] = {position(407, 232, 0)} -- Bula
QuestTarget[63] = {position(407, 232, 0)} -- Bula
QuestTarget[64] = {position(407, 232, 0)} -- Bula
QuestTarget[65] = {position(407, 232, 0)} -- Bula
QuestTarget[66] = {position(407, 232, 0)} -- Bula
QuestTarget[67] = {position(407, 232, 0)} -- Bula
QuestTarget[68] = {position(407, 232, 0)} -- Bula
QuestTarget[69] = {position(407, 232, 0)} -- Bula
QuestTarget[70] = {position(407, 232, 0)} -- Bula
QuestTarget[71] = {position(407, 232, 0)} -- Bula
QuestTarget[72] = {position(407, 232, 0)} -- Bula
QuestTarget[73] = {position(407, 232, 0)} -- Bula
QuestTarget[74] = {position(407, 232, 0)} -- Bula
QuestTarget[75] = {position(407, 232, 0)} -- Bula
QuestTarget[76] = {position(407, 232, 0)} -- Bula
QuestTarget[77] = {position(407, 232, 0)} -- Bula
QuestTarget[78] = {position(407, 232, 0)} -- Bula
QuestTarget[79] = {position(407, 232, 0)} -- Bula
QuestTarget[80] = {position(407, 232, 0)} -- Bula
QuestTarget[81] = {position(407, 232, 0)} -- Bula
QuestTarget[82] = {position(407, 232, 0)} -- Bula
QuestTarget[83] = {position(407, 232, 0)} -- Bula
QuestTarget[84] = {position(407, 232, 0)} -- Bula
QuestTarget[85] = {position(407, 232, 0)} -- Bula
QuestTarget[86] = {position(407, 232, 0)} -- Bula
QuestTarget[87] = {position(407, 232, 0)} -- Bula
QuestTarget[88] = {position(407, 232, 0)} -- Bula
QuestTarget[89] = {position(407, 232, 0)} -- Bula
QuestTarget[90] = {position(407, 232, 0)} -- Bula
QuestTarget[91] = {position(407, 232, 0)} -- Bula
QuestTarget[92] = {position(407, 232, 0)} -- Bula
QuestTarget[93] = {position(407, 232, 0)} -- Bula
QuestTarget[94] = {position(407, 232, 0)} -- Bula
QuestTarget[95] = {position(407, 232, 0)} -- Bula
QuestTarget[96] = {position(407, 232, 0)} -- Bula
QuestTarget[97] = {position(407, 232, 0)} -- Bula
QuestTarget[98] = {position(407, 232, 0)} -- Bula
QuestTarget[99] = {position(407, 232, 0)} -- Bula
QuestTarget[100] = {position(407, 232, 0)} -- Bula
QuestTarget[101] = {position(407, 232, 0)} -- Bula
QuestTarget[102] = {position(407, 232, 0)} -- Bula
QuestTarget[103] = {position(407, 232, 0)} -- Bula
QuestTarget[104] = {position(407, 232, 0)} -- Bula
QuestTarget[105] = {position(407, 232, 0)} -- Bula
QuestTarget[106] = {position(407, 232, 0)} -- Bula
QuestTarget[107] = {position(407, 232, 0)} -- Bula
QuestTarget[108] = {position(407, 232, 0)} -- Bula
QuestTarget[109] = {position(407, 232, 0)} -- Bula
QuestTarget[110] = {position(407, 232, 0)} -- Bula
QuestTarget[111] = {position(407, 232, 0)} -- Bula
QuestTarget[112] = {position(407, 232, 0)} -- Bula
QuestTarget[113] = {position(407, 232, 0)} -- Bula
QuestTarget[114] = {position(407, 232, 0)} -- Bula
QuestTarget[115] = {position(407, 232, 0)} -- Bula
QuestTarget[116] = {position(407, 232, 0)} -- Bula
QuestTarget[117] = {position(407, 232, 0)} -- Bula
QuestTarget[118] = {position(407, 232, 0)} -- Bula
QuestTarget[119] = {position(407, 232, 0)} -- Bula
QuestTarget[120] = {position(407, 232, 0)} -- Bula
QuestTarget[121] = {position(407, 232, 0)} -- Bula
QuestTarget[122] = {position(407, 232, 0)} -- Bula
QuestTarget[123] = {position(407, 232, 0)} -- Bula
QuestTarget[124] = {position(407, 232, 0)} -- Bula
QuestTarget[125] = {position(407, 232, 0)} -- Bula
QuestTarget[126] = {position(407, 232, 0)} -- Bula
QuestTarget[127] = {position(407, 232, 0)} -- Bula
QuestTarget[128] = {position(407, 232, 0)} -- Bula
QuestTarget[129] = {position(407, 232, 0)} -- Bula
QuestTarget[130] = {position(407, 232, 0)} -- Bula
QuestTarget[131] = {position(407, 232, 0)} -- Bula
QuestTarget[132] = {position(407, 232, 0)} -- Bula
QuestTarget[133] = {position(407, 232, 0)} -- Bula
QuestTarget[134] = {position(407, 232, 0)} -- Bula
QuestTarget[135] = {position(407, 232, 0)} -- Bula
QuestTarget[136] = {position(407, 232, 0)} -- Bula
QuestTarget[137] = {position(407, 232, 0)} -- Bula
QuestTarget[138] = {position(407, 232, 0)} -- Bula
QuestTarget[139] = {position(407, 232, 0)} -- Bula
QuestTarget[140] = {position(407, 232, 0)} -- Bula
QuestTarget[141] = {position(407, 232, 0)} -- Bula
QuestTarget[142] = {position(407, 232, 0)} -- Bula
QuestTarget[143] = {position(407, 232, 0)} -- Bula
QuestTarget[144] = {position(407, 232, 0)} -- Bula
QuestTarget[145] = {position(407, 232, 0)} -- Bula
QuestTarget[146] = {position(407, 232, 0)} -- Bula
QuestTarget[147] = {position(407, 232, 0)} -- Bula
QuestTarget[148] = {position(407, 232, 0)} -- Bula
QuestTarget[149] = {position(407, 232, 0)} -- Bula
QuestTarget[150] = {position(407, 232, 0)} -- Bula
QuestTarget[151] = {position(407, 232, 0)} -- Bula
QuestTarget[152] = {position(407, 232, 0)} -- Bula
QuestTarget[153] = {position(407, 232, 0)} -- Bula
QuestTarget[154] = {position(407, 232, 0)} -- Bula
QuestTarget[155] = {position(407, 232, 0)} -- Bula
QuestTarget[156] = {position(407, 232, 0)} -- Bula
QuestTarget[157] = {position(407, 232, 0)} -- Bula
QuestTarget[158] = {position(407, 232, 0)} -- Bula
QuestTarget[159] = {position(407, 232, 0)} -- Bula
QuestTarget[160] = {position(407, 232, 0)} -- Bula
QuestTarget[161] = {position(407, 232, 0)} -- Bula
QuestTarget[162] = {position(407, 232, 0)} -- Bula
QuestTarget[163] = {position(407, 232, 0)} -- Bula
QuestTarget[164] = {position(407, 232, 0)} -- Bula
QuestTarget[165] = {position(407, 232, 0)} -- Bula
QuestTarget[166] = {position(407, 232, 0)} -- Bula
QuestTarget[167] = {position(407, 232, 0)} -- Bula
QuestTarget[168] = {position(407, 232, 0)} -- Bula
QuestTarget[169] = {position(407, 232, 0)} -- Bula
QuestTarget[170] = {position(407, 232, 0)} -- Bula
QuestTarget[171] = {position(407, 232, 0)} -- Bula
QuestTarget[172] = {position(407, 232, 0)} -- Bula
QuestTarget[173] = {position(407, 232, 0)} -- Bula
QuestTarget[174] = {position(407, 232, 0)} -- Bula
QuestTarget[175] = {position(407, 232, 0)} -- Bula
QuestTarget[176] = {position(407, 232, 0)} -- Bula
QuestTarget[177] = {position(407, 232, 0)} -- Bula
QuestTarget[178] = {position(407, 232, 0)} -- Bula
QuestTarget[179] = {position(407, 232, 0)} -- Bula
QuestTarget[180] = {position(407, 232, 0)} -- Bula
QuestTarget[181] = {position(407, 232, 0)} -- Bula
QuestTarget[182] = {position(407, 232, 0)} -- Bula
QuestTarget[183] = {position(407, 232, 0)} -- Bula
QuestTarget[184] = {position(407, 232, 0)} -- Bula
QuestTarget[185] = {position(407, 232, 0)} -- Bula
QuestTarget[186] = {position(407, 232, 0)} -- Bula
QuestTarget[187] = {position(407, 232, 0)} -- Bula
QuestTarget[188] = {position(407, 232, 0)} -- Bula
QuestTarget[189] = {position(407, 232, 0)} -- Bula

-- Insert the quest status which is reached at the end of the quest
FINAL_QUEST_STATUS = 0


function QuestTitle(user)
    return base.common.GetNLS(user, Title[GERMAN], Title[ENGLISH])
end

function QuestDescription(user, status)
    local german = Description[GERMAN][status] or ""
    local english = Description[ENGLISH][status] or ""

    return base.common.GetNLS(user, german, english)
end

function QuestStart()
    return Start
end

function QuestTargets(user, status)
    return QuestTarget[status]
end

function QuestFinalStatus()
    return FINAL_QUEST_STATUS
end
