--[[
Illarion Server

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>. 
]]
-- INSERT INTO "quests" ("qst_id", "qst_script") VALUES (184, 'quest.maelyrra_umrielyth_184_runewick');

require("base.common")
module("quest.maelyrra_umrielyth_184_runewick", package.seeall)

GERMAN = Player.german
ENGLISH = Player.english

-- Insert the quest title here, in both languages
Title = {}
Title[GERMAN] = "Die Forscher"
Title[ENGLISH] = "The Researcher"

-- Insert an extensive description of each status here, in both languages
-- Make sure that the player knows exactly where to go and what to do
Description = {}
Description[GERMAN] = {}
Description[ENGLISH] = {}

Description[GERMAN][1] = "Informationsbedarf für die Don gesammelt. Scout für den Bereich Informations-und töten vier Wespen, euer Lohn ist einem Silberstück."
Description[GERMAN][2] = "."
Description[GERMAN][3] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von einem Silberstück an denjenigen auszuzahlen, der vier Käfer erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][4] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von einem Silberstück an denjenigen auszuzahlen, der vier Käfer erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][5] = "Kehre zu Bula Glasha zurück, um deine Belohnung zu erhalten."
Description[GERMAN][6] = "Die Gegend um Galmair geworden zunehmenden gewalttätigen und das ist der Don-Gewinne zu behindern. Scout für den Bereich Informations-und töten acht Wespen, euer Lohn ist zwei Silberstücke."
Description[GERMAN][7] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][8] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][9] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][10] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][11] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][12] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][13] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][14] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][15] = "Intelligence-Berichte sind für die Sicherheit der Galmair nötig. Scout für den Bereich Informations-und töten zwölf Wespen, euer Lohn ist drei Silbermünzen."
Description[GERMAN][16] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][17] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][18] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][19] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][20] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][21] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][22] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][23] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][24] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][25] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][26] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][27] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][28] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][29] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][30] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][31] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][32] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][33] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][34] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][35] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][36] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][37] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][38] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][39] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][40] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][41] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][42] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][43] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][44] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][45] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][46] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][47] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][48] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][49] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][50] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][51] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][52] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][53] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][54] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][55] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][56] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][57] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][58] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][59] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][60] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][61] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][62] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][63] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][64] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][65] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][66] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][67] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][68] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][69] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][70] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][71] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][72] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][73] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][74] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][75] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][76] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][77] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][78] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][79] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][80] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][81] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][82] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][83] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][84] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][85] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][86] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][87] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][88] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][89] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][90] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][91] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][92] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][93] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][94] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][95] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][96] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][97] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][98] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][99] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][100] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][101] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][102] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][103] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][104] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][105] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][106] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][107] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][108] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][109] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][110] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][111] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][112] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][113] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][114] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][115] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][116] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][117] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][118] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][119] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][120] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][121] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][122] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][123] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][124] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][125] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][126] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][127] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][128] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][129] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][130] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][131] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][132] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][133] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][134] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][135] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][136] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][137] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][138] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][139] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][140] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][141] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][142] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][143] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][144] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][145] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][146] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][147] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][148] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][149] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][150] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][151] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][152] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][153] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][154] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][155] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][156] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][157] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][158] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][159] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][160] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][161] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][162] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][163] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][164] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][165] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][166] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][167] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][168] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][169] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][170] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][171] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][172] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][173] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][174] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][175] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][176] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][177] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][178] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][179] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][180] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][181] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][182] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][183] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][184] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][185] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][186] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][187] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][188] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][189] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."

Description[ENGLISH][1] = "There is research to be done and help required getting the information.  Kill four slimes and bring the evidence, the reward is one silver coin."
Description[ENGLISH][2] = "There is research to be done and help required getting the information.  Kill four slimes and bring the evidence, the reward is one silver coin."
Description[ENGLISH][3] = "There is research to be done and help required getting the information.  Kill four slimes and bring the evidence, the reward is one silver coin."
Description[ENGLISH][4] = "There is research to be done and help required getting the information.  Kill four slimes and bring the evidence, the reward is one silver coin."
Description[ENGLISH][5] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][6] = "Runewick is the cornerstone of academic research.  Please assist by killing eight slimes and bringing back the evidence.  Your reward is two silver coins."
Description[ENGLISH][7] = "Runewick is the cornerstone of academic research.  Please assist by killing eight slimes and bringing back the evidence.  Your reward is two silver coins."
Description[ENGLISH][8] = "Runewick is the cornerstone of academic research.  Please assist by killing eight slimes and bringing back the evidence.  Your reward is two silver coins."
Description[ENGLISH][9] = "Runewick is the cornerstone of academic research.  Please assist by killing eight slimes and bringing back the evidence.  Your reward is two silver coins."
Description[ENGLISH][10] = "Runewick is the cornerstone of academic research.  Please assist by killing eight slimes and bringing back the evidence.  Your reward is two silver coins."
Description[ENGLISH][11] = "Runewick is the cornerstone of academic research.  Please assist by killing eight slimes and bringing back the evidence.  Your reward is two silver coins."
Description[ENGLISH][12] = "Runewick is the cornerstone of academic research.  Please assist by killing eight slimes and bringing back the evidence.  Your reward is two silver coins."
Description[ENGLISH][13] = "Runewick is the cornerstone of academic research.  Please assist by killing eight slimes and bringing back the evidence.  Your reward is two silver coins."
Description[ENGLISH][14] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][15] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][16] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][17] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][18] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][19] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][20] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][21] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][22] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][23] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][24] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][25] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][26] = "Research the area and kill twelve slimes bringing back the evidence. Your reward is three silver coins."
Description[ENGLISH][27] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][28] = "There is research to be done and help required getting the information.  Kill four dogs and bring the evidence, the reward is two silver coins."
Description[ENGLISH][29] = "There is research to be done and help required getting the information.  Kill four dogs and bring the evidence, the reward is two silver coins."
Description[ENGLISH][30] = "There is research to be done and help required getting the information.  Kill four dogs and bring the evidence, the reward is two silver coins."
Description[ENGLISH][31] = "There is research to be done and help required getting the information.  Kill four dogs and bring the evidence, the reward is two silver coins."
Description[ENGLISH][32] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][33] = "Runewick is the cornerstone of academic research.  Please assist by killing eight dogs and bringing back the evidence.  Your reward is four silver coins."
Description[ENGLISH][34] = "Runewick is the cornerstone of academic research.  Please assist by killing eight dogs and bringing back the evidence.  Your reward is four silver coins."
Description[ENGLISH][35] = "Runewick is the cornerstone of academic research.  Please assist by killing eight dogs and bringing back the evidence.  Your reward is four silver coins."
Description[ENGLISH][36] = "Runewick is the cornerstone of academic research.  Please assist by killing eight dogs and bringing back the evidence.  Your reward is four silver coins."
Description[ENGLISH][37] = "Runewick is the cornerstone of academic research.  Please assist by killing eight dogs and bringing back the evidence.  Your reward is four silver coins."
Description[ENGLISH][38] = "Runewick is the cornerstone of academic research.  Please assist by killing eight dogs and bringing back the evidence.  Your reward is four silver coins."
Description[ENGLISH][39] = "Runewick is the cornerstone of academic research.  Please assist by killing eight dogs and bringing back the evidence.  Your reward is four silver coins."
Description[ENGLISH][40] = "Runewick is the cornerstone of academic research.  Please assist by killing eight dogs and bringing back the evidence.  Your reward is four silver coins."
Description[ENGLISH][41] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][42] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][43] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][44] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][45] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][46] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][47] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][48] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][49] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][50] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][51] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][52] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][53] = "Research the area and kill twelve dogs bringing back the evidence. Your reward is six silver coins."
Description[ENGLISH][54] = "Return to  Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][55] = "There is research to be done and help required getting the information.  Kill four wolves and bring the evidence, the reward is three silver coins."
Description[ENGLISH][56] = "There is research to be done and help required getting the information.  Kill four wolves and bring the evidence, the reward is three silver coins."
Description[ENGLISH][57] = "There is research to be done and help required getting the information.  Kill four wolves and bring the evidence, the reward is three silver coins."
Description[ENGLISH][58] = "There is research to be done and help required getting the information.  Kill four wolves and bring the evidence, the reward is three silver coins."
Description[ENGLISH][59] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][60] = "Runewick is the cornerstone of academic research.  Please assist by killing eight wolves and bringing back the evidence.  Your reward is six silver coins."
Description[ENGLISH][61] = "Runewick is the cornerstone of academic research.  Please assist by killing eight wolves and bringing back the evidence.  Your reward is six silver coins."
Description[ENGLISH][62] = "Runewick is the cornerstone of academic research.  Please assist by killing eight wolves and bringing back the evidence.  Your reward is six silver coins."
Description[ENGLISH][63] = "Runewick is the cornerstone of academic research.  Please assist by killing eight wolves and bringing back the evidence.  Your reward is six silver coins."
Description[ENGLISH][64] = "Runewick is the cornerstone of academic research.  Please assist by killing eight wolves and bringing back the evidence.  Your reward is six silver coins."
Description[ENGLISH][65] = "Runewick is the cornerstone of academic research.  Please assist by killing eight wolves and bringing back the evidence.  Your reward is six silver coins."
Description[ENGLISH][66] = "Runewick is the cornerstone of academic research.  Please assist by killing eight wolves and bringing back the evidence.  Your reward is six silver coins."
Description[ENGLISH][67] = "Runewick is the cornerstone of academic research.  Please assist by killing eight wolves and bringing back the evidence.  Your reward is six silver coins."
Description[ENGLISH][68] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][69] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][70] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][71] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][72] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][73] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][74] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][75] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][76] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][77] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][78] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][79] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][80] = "Research the area and kill twelve wolves bringing back the evidence. Your reward is nine silver coins."
Description[ENGLISH][81] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][82] = "There is research to be done and help required getting the information.  Kill four bears and bring the evidence, the reward is four silver coins."
Description[ENGLISH][83] = "There is research to be done and help required getting the information.  Kill four bears and bring the evidence, the reward is four silver coins."
Description[ENGLISH][84] = "There is research to be done and help required getting the information.  Kill four bears and bring the evidence, the reward is four silver coins."
Description[ENGLISH][85] = "There is research to be done and help required getting the information.  Kill four bears and bring the evidence, the reward is four silver coins."
Description[ENGLISH][86] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][87] = "Runewick is the cornerstone of academic research.  Please assist by killing eight bears and bringing back the evidence.  Your reward is eight silver coins."
Description[ENGLISH][88] = "Runewick is the cornerstone of academic research.  Please assist by killing eight bears and bringing back the evidence.  Your reward is eight silver coins."
Description[ENGLISH][89] = "Runewick is the cornerstone of academic research.  Please assist by killing eight bears and bringing back the evidence.  Your reward is eight silver coins."
Description[ENGLISH][90] = "Runewick is the cornerstone of academic research.  Please assist by killing eight bears and bringing back the evidence.  Your reward is eight silver coins."
Description[ENGLISH][91] = "Runewick is the cornerstone of academic research.  Please assist by killing eight bears and bringing back the evidence.  Your reward is eight silver coins."
Description[ENGLISH][92] = "Runewick is the cornerstone of academic research.  Please assist by killing eight bears and bringing back the evidence.  Your reward is eight silver coins."
Description[ENGLISH][93] = "Runewick is the cornerstone of academic research.  Please assist by killing eight bears and bringing back the evidence.  Your reward is eight silver coins."
Description[ENGLISH][94] = "Runewick is the cornerstone of academic research.  Please assist by killing eight bears and bringing back the evidence.  Your reward is eight silver coins."
Description[ENGLISH][95] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][96] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][97] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][98] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][99] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][100] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][101] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][102] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][103] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][104] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][105] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][106] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][107] = "Research the area and kill twelve bears bringing back the evidence. Your reward is twelve silver coins."
Description[ENGLISH][108] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][109] = "There is research to be done and help required getting the information.  Kill four humans and bring the evidence, the reward is six silver coins."
Description[ENGLISH][110] = "There is research to be done and help required getting the information.  Kill four humans and bring the evidence, the reward is six silver coins."
Description[ENGLISH][111] = "There is research to be done and help required getting the information.  Kill four humans and bring the evidence, the reward is six silver coins."
Description[ENGLISH][112] = "There is research to be done and help required getting the information.  Kill four humans and bring the evidence, the reward is six silver coins."
Description[ENGLISH][113] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][114] = "Runewick is the cornerstone of academic research.  Please assist by killing eight humans and bringing back the evidence.  Your reward is twelve silver coins."
Description[ENGLISH][115] = "Runewick is the cornerstone of academic research.  Please assist by killing eight humans and bringing back the evidence.  Your reward is twelve silver coins."
Description[ENGLISH][116] = "Runewick is the cornerstone of academic research.  Please assist by killing eight humans and bringing back the evidence.  Your reward is twelve silver coins."
Description[ENGLISH][117] = "Runewick is the cornerstone of academic research.  Please assist by killing eight humans and bringing back the evidence.  Your reward is twelve silver coins."
Description[ENGLISH][118] = "Runewick is the cornerstone of academic research.  Please assist by killing eight humans and bringing back the evidence.  Your reward is twelve silver coins."
Description[ENGLISH][119] = "Runewick is the cornerstone of academic research.  Please assist by killing eight humans and bringing back the evidence.  Your reward is twelve silver coins."
Description[ENGLISH][120] = "Runewick is the cornerstone of academic research.  Please assist by killing eight humans and bringing back the evidence.  Your reward is twelve silver coins."
Description[ENGLISH][121] = "Runewick is the cornerstone of academic research.  Please assist by killing eight humans and bringing back the evidence.  Your reward is twelve silver coins."
Description[ENGLISH][122] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][123] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][124] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][125] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][126] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][127] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][128] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][129] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][130] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][131] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][132] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][133] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][134] = "Research the area and kill twelve humans bringing back the evidence. Your reward is eighteen silver coins."
Description[ENGLISH][135] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][136] = "There is research to be done and help required getting the information.  Kill four thieves and bring the evidence, the reward is eight silver coins."
Description[ENGLISH][137] = "There is research to be done and help required getting the information.  Kill four thieves and bring the evidence, the reward is eight silver coins."
Description[ENGLISH][138] = "There is research to be done and help required getting the information.  Kill four thieves and bring the evidence, the reward is eight silver coins."
Description[ENGLISH][139] = "There is research to be done and help required getting the information.  Kill four thieves and bring the evidence, the reward is eight silver coins."
Description[ENGLISH][140] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][141] = "Runewick is the cornerstone of academic research.  Please assist by killing eight thieves and bringing back the evidence.  Your reward is sixteen silver coins."
Description[ENGLISH][142] = "Runewick is the cornerstone of academic research.  Please assist by killing eight thieves and bringing back the evidence.  Your reward is sixteen silver coins."
Description[ENGLISH][143] = "Runewick is the cornerstone of academic research.  Please assist by killing eight thieves and bringing back the evidence.  Your reward is sixteen silver coins."
Description[ENGLISH][144] = "Runewick is the cornerstone of academic research.  Please assist by killing eight thieves and bringing back the evidence.  Your reward is sixteen silver coins."
Description[ENGLISH][145] = "Runewick is the cornerstone of academic research.  Please assist by killing eight thieves and bringing back the evidence.  Your reward is sixteen silver coins."
Description[ENGLISH][146] = "Runewick is the cornerstone of academic research.  Please assist by killing eight thieves and bringing back the evidence.  Your reward is sixteen silver coins."
Description[ENGLISH][147] = "Runewick is the cornerstone of academic research.  Please assist by killing eight thieves and bringing back the evidence.  Your reward is sixteen silver coins."
Description[ENGLISH][148] = "Runewick is the cornerstone of academic research.  Please assist by killing eight thieves and bringing back the evidence.  Your reward is sixteen silver coins."
Description[ENGLISH][149] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][150] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][151] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][152] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][153] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][154] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][155] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][156] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][157] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][158] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][159] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][160] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][161] = "Research the area and kill twelve thieves bringing back the evidence. Your reward is twenty four silver coins."
Description[ENGLISH][162] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][163] = "There is research to be done and help required getting the information.  Kill four zombies and bring the evidence, the reward is ten silver coins."
Description[ENGLISH][164] = "There is research to be done and help required getting the information.  Kill four zombies and bring the evidence, the reward is ten silver coins."
Description[ENGLISH][165] = "There is research to be done and help required getting the information.  Kill four zombies and bring the evidence, the reward is ten silver coins."
Description[ENGLISH][166] = "There is research to be done and help required getting the information.  Kill four zombies and bring the evidence, the reward is ten silver coins."
Description[ENGLISH][167] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][168] = "Runewick is the cornerstone of academic research.  Please assist by killing eight zombies and bringing back the evidence.  Your reward is twenty silver coins."
Description[ENGLISH][169] = "Runewick is the cornerstone of academic research.  Please assist by killing eight zombies and bringing back the evidence.  Your reward is twenty silver coins."
Description[ENGLISH][170] = "Runewick is the cornerstone of academic research.  Please assist by killing eight zombies and bringing back the evidence.  Your reward is twenty silver coins."
Description[ENGLISH][171] = "Runewick is the cornerstone of academic research.  Please assist by killing eight zombies and bringing back the evidence.  Your reward is twenty silver coins."
Description[ENGLISH][172] = "Runewick is the cornerstone of academic research.  Please assist by killing eight zombies and bringing back the evidence.  Your reward is twenty silver coins."
Description[ENGLISH][173] = "Runewick is the cornerstone of academic research.  Please assist by killing eight zombies and bringing back the evidence.  Your reward is twenty silver coins."
Description[ENGLISH][174] = "Runewick is the cornerstone of academic research.  Please assist by killing eight zombies and bringing back the evidence.  Your reward is twenty silver coins."
Description[ENGLISH][175] = "Runewick is the cornerstone of academic research.  Please assist by killing eight zombies and bringing back the evidence.  Your reward is twenty silver coins."
Description[ENGLISH][176] = "Return to Maelyrra Umrielyth to claim your reward."
Description[ENGLISH][177] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][178] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][179] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][180] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][181] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][182] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][183] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][184] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][185] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][186] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][187] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][188] = "Research the area and kill twelve zombies bringing back the evidence. Your reward is thirty silver coins."
Description[ENGLISH][189] = "Return to Maelyrra Umrielyth to claim your reward."


-- Insert the position of the quest start here (probably the position of an NPC or item)
Start = {861, 809, 0}

-- For each status insert a list of positions where the quest will continue, i.e. a new status can be reached there
QuestTarget = {}
QuestTarget[1] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[2] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[3] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[4] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[5] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[6] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[7] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[8] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[9] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[10] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[11] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[12] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[13] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[14] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[15] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[16] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[17] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[18] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[19] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[20] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[21] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[22] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[23] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[24] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[25] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[26] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[27] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[28] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[29] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[30] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[31] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[32] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[33] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[34] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[35] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[36] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[37] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[38] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[39] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[40] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[41] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[42] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[43] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[44] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[45] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[46] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[47] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[48] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[49] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[50] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[51] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[52] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[53] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[54] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[55] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[56] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[57] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[58] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[59] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[60] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[61] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[62] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[63] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[64] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[65] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[66] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[67] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[68] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[69] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[70] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[71] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[72] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[73] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[74] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[75] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[76] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[77] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[78] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[79] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[80] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[81] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[82] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[83] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[84] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[85] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[86] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[87] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[88] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[89] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[90] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[91] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[92] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[93] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[94] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[95] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[96] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[97] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[98] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[99] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[100] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[101] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[102] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[103] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[104] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[105] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[106] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[107] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[108] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[109] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[110] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[111] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[112] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[113] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[114] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[115] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[116] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[117] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[118] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[119] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[120] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[121] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[122] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[123] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[124] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[125] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[126] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[127] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[128] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[129] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[130] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[131] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[132] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[133] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[134] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[135] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[136] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[137] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[138] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[139] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[140] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[141] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[142] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[143] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[144] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[145] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[146] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[147] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[148] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[149] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[150] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[151] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[152] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[153] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[154] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[155] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[156] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[157] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[158] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[159] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[160] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[161] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[162] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[163] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[164] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[165] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[166] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[167] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[168] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[169] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[170] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[171] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[172] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[173] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[174] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[175] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[176] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[177] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[178] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[179] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[180] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[181] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[182] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[183] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[184] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[185] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[186] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[187] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[188] = {position(861, 809, 0)} -- Maelyrra
QuestTarget[189] = {position(861, 809, 0)} -- Maelyrra

-- Insert the quest status which is reached at the end of the quest
FINAL_QUEST_STATUS = 0


function QuestTitle(user)
    return base.common.GetNLS(user, Title[GERMAN], Title[ENGLISH])
end

function QuestDescription(user, status)
    local german = Description[GERMAN][status] or ""
    local english = Description[ENGLISH][status] or ""

    return base.common.GetNLS(user, german, english)
end

function QuestStart()
    return Start
end

function QuestTargets(user, status)
    return QuestTarget[status]
end

function QuestFinalStatus()
    return FINAL_QUEST_STATUS
end
